; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATmega48]
platform = atmelavr
board = ATmega48
;upload_command=avrdude -c usbasp -p m48 -U flash:w:.pio/build/atmega48/firmware.hex:a
board_build.f_cpu = 1000000L

;
monitor_port = COM8
monitor_speed = 4800
usb_port = usb
upload_protocol =  usbasp ;avrispmkii 
upload_flags =
    -e
    -B64


